version: "3"

services:
  database:
    image: postgres
    container_name: answered_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${USERNAME_DATABASE}
      - POSTGRES_PASSWORD=${PASSWORD_DATABASE}
      - POSTGRES_DB=app
    volumes:
      - pgdata:/data/postgres

volumes: 
  pgdata: 
    driver: local